[gravity]
domain = "default"
host = "192.168.8.227"
port = 32803
pingInterval = 10
maxPingsOutstanding = 3
maxReconnects = -1
accessToken = ""
publishBatchSize = 1000

[source]
config = "./settings/sources.json"

[store]
enabled = true
path = "./statestore"
